// react-assigment/src/App.jsx
import React from 'react';
import './App.scss';
import logo from './assets/images/logo.png'

class App extends React.Component {
  render() {
    return (
      <header className="header">
        <img className="header__logo" alt="" src={logo}></img>
        <a className="header__icon"><i className="fas fa-bars fa-3x"></i></a>
        <nav className="header__nav">
          <ul className="header__nav__elements">
            <li><a href="#">Directorio de Agentes</a></li>
            <li><a href="#">Contacto</a></li>
            <li><a href="#">Ingresar</a></li>
          </ul>
        </nav>
      </header>
    );
  } 
}

export default App;

// AngularAssigment/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'AngularAssigment';
}

<header class="header">
  <img class="header__logo" src="../assets/images/logo.png">
  <a class="header__icon"><i class="fas fa-bars fa-3x"></i></a>
  <nav class="header__nav">
      <ul class="header__nav__elements">
          <li><a href="#">Directorio de Agentes</a></li>
          <li><a href="#">Contacto</a></li>
          <li><a href="#">Ingresar</a></li>
      </ul>
  </nav>
</header>
<app-main-content></app-main-content>
<app-footer></app-footer>
