// react-assigment/src/components/MainContent/MainContent.jsx
import React from 'react';
import './MainContent.scss';
import CompanyService  from '../../services/companies';
import certified from '../../assets/images/certified.png';
import agentImg from '../../assets/images/chuck.jpg';

class MainContent extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      companies: [],
      filter: '',
    }

    this.getCompanies = this.getCompanies.bind(this);
  }

  componentWillMount() {
    this.getCompanies();
  }

  handleChange(e) {
    if (e.target.value.length >2){
      this.setState({
        filter: e.target.value.toLowerCase()
      })  
    } else {
      this.setState({
        filter: ''
      }) 
    }
  }

  /**
   * This function gets all companies from the service
   */
  getCompanies() {
    CompanyService.getCompanies().then( (response) => {
      this.setState({ companies: response.data.companies})
    });
  }

  render() {
    const companies = this.state.companies.filter(company => company.name.toLowerCase().includes(this.state.filter)).map ( company => (
      <article className="container__body__item">
          <div className="container__body__item__header">
              <h1 className="container__body__item__header__title">{company.name}</h1>
              { company.isCertified ? <img className="container__body__item__header__logo" src={certified}/> : null }
          </div>
          <div className="container__body__item__line"></div>
          <section className="container__body__item__section">
              <img className="container__body__item__section__img" src={agentImg}/>
              <p className="container__body__item__section__info">{company.description}</p>
          </section>
          <footer className="container__body__item__footer">
              <p className="container__body__item__footer__tittle">Desde ${company.rate} {company.hours}/hrs</p>
              <button className="container__body__item__footer__button">Contratar</button>
          </footer>
      </article>
    ))
    return (
      <div>
        <div className="search">
        </div>

        <div className="container">
          <div className="container__header">
            <h1 className="container__header__title container__header__title--black">Los Mejores agentes de seguridad</h1>
            <input className="container__header__input" type="search" placeholder="Buscar por Ubicación" onChange={(e) => {this.handleChange(e)}} />
            <button className="container__header__button"/>
          </div>
          <div className="container__body" id="box">
                { companies }
            </div>
        </div>
      </div>
    );
  } 
}

export default MainContent;

// AngularAssigment/src/app/main-content/main-content.component.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';
import { Observable } from 'rxjs';
import { FilterPipe } from 'ngx-filter-pipe';

@Component({
  selector: 'app-main-content',
  templateUrl: './main-content.component.html',
  styleUrls: ['./main-content.component.scss']
})
export class MainContentComponent implements OnInit {

  companies$: Object;
  searchName: any = {name: ''};

  constructor(private data: DataService, private filter: FilterPipe) { 

  }

  ngOnInit() {
    this.data.getCompanies().subscribe(
      data => this.companies$ = data
    )
  }

  checkLength(e){
    if (e.length > 2)
      this.searchName.name = String(e);
    else 
      this.searchName.name = '';
  }

  

}

<div class="search">
</div>

<div class="container">
    <div class="container__header">
        <h1 class="container__header__title container__header__title--black">Los Mejores agentes de seguridad</h1>
        <input class="container__header__input" [(ngModel)]="searchName.name" (ngModelChange)="checkLength($event)" type="search"  placeholder="Buscar por Ubicación">
        <button class="container__header__button"><img src="../../assets/images/search.png"></button>
    </div>
    <div class="container__body" id="box" *ngIf="companies$">
        <article class="container__body__item" *ngFor="let company of companies$.companies | filterBy: searchName ">
            <div class="container__body__item__header">
                <h1 class="container__body__item__header__title">{{company.name}}</h1>
                <img *ngIf="company.isCertified" class="container__body__item__header__logo" src="../../assets/images/certified.png">
            </div>
            <div class="container__body__item__line"></div>
            <section class="container__body__item__section">
                <img class="container__body__item__section__img" src="../../assets/images/chuck.jpg">
                <p class="container__body__item__section__info">{{company.description}}</p>
            </section>
            <footer class="container__body__item__footer">
                <p class="container__body__item__footer__tittle">Desde ${{company.rate}} {{company.hours}}/hrs</p>
                <button class="container__body__item__footer__button">Contratar</button>
            </footer>
        </article>
    </div>
</div>
